spring.application.name=iot-home-back
server.port=3333

#spring.profiles.active=dev
spring.profiles.active=test

# Para que o JPA traga a associaçãoo de tabelas ex. os Tickets do User
spring.jpa.open-in-view=true